# Generated by Django 5.0.7 on 2024-07-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='invoices/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True)),
                ('image_path', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
