# Generated by Django 5.0.7 on 2024-07-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('similarity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='hash',
            field=models.CharField(default=1, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
