# Generated by Django 5.0.7 on 2024-08-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('similarity', '0002_invoice_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='hash',
            field=models.CharField(max_length=64),
        ),
    ]
